### batch can json
POST http://{{host}}/streams
Content-Type: application/json

{
  "sql": "CREATE STREAM batchCanJson() WITH (TYPE=\"mqtt\",FORMAT=\"json\",DATASOURCE=\"sim\",SHARED=\"true\", CONF_KEY=\"ten_sec\");"
}

### Get all
PUT http://{{host}}/rules/ruleBatchAll
Content-Type: application/json

{
  "id": "ruleBatchAll",
  "name": "测试所有数据",
  "sql": "SELECT * FROM batchCanJson",
  "actions": [
    {
      "mqtt": {
        "server": "tcp://syno.home:1883",
        "topic": "result/batch",
        "sendSingle": true
      }
    }
  ],
  "options": {
    "debug": true
  }
}

### Send multiple batch data
#{"frames":[{"id":485,"data":"7c00019000000000","bus":4,"d":0,"t":0},{"id":555,"data":"2b020000080000005465737400000000","bus":4,"d":0,"t":0}]}

### single can json with batch can
PUT http://{{host}}/streams/canjson
Content-Type: application/json

{
  "sql": "CREATE STREAM canjson() WITH (TYPE=\"mqtt\",FORMAT=\"json\",DATASOURCE=\"sim2\",SHARED=\"true\", CONF_KEY=\"canjson\");"
}

### Get all
POST http://{{host}}/rules
Content-Type: application/json

{
  "id": "ruleJsonAll",
  "name": "测试所有数据",
  "sql": "SELECT * FROM canjson",
  "actions": [
    {
      "mqtt": {
        "server": "tcp://syno.home:1883",
        "topic": "result/json",
        "sendSingle": true
      }
    }
  ],
  "options": {
    "debug": true
  }
}

### Send data
#{"frames":[{"id":555,"data":"KwIAAAgAAABUZXN0AAAAAA==","bus":4,"d":0,"t":0}]}

### rate limit for can
PUT http://{{host}}/streams/batchCan
Content-Type: application/json

{
  "sql": "CREATE STREAM batchCan() WITH (TYPE=\"mqtt\",FORMAT=\"can\",DATASOURCE=\"sim3\",SHARED=\"true\", SCHEMAID=\"scene\/dbc\",CONF_KEY=\"batch\");"
}

### Get all
POST http://{{host}}/rules
Content-Type: application/json

{
  "id": "ruleBatchCan",
  "name": "测试所有数据",
  "sql": "SELECT * FROM batchCan",
  "actions": [
    {
      "mqtt": {
        "server": "tcp://syno.home:1883",
        "topic": "result/batchcan",
        "sendSingle": true
      }
    }
  ],
  "options": {
    "debug": true
  }
}

### Send data
#2b020000080000005465737400000000
#e5010000080000005465737400000000

### rate limit for can
POST http://{{host}}/streams
Content-Type: application/json

{
  "sql": "CREATE STREAM batchCanMerge() WITH (TYPE=\"mqtt\",FORMAT=\"can\",DATASOURCE=\"sim4\",SHARED=\"true\", SCHEMAID=\"scene\/dbc\",CONF_KEY=\"batchMerge\");"
}

### Get all
POST http://{{host}}/rules
Content-Type: application/json

{
  "id": "ruleBatchMerge",
  "name": "测试所有数据",
  "sql": "SELECT * FROM batchCanMerge",
  "actions": [
    {
      "mqtt": {
        "server": "tcp://syno.home:1883",
        "topic": "result/batchcanmerge",
        "sendSingle": true
      }
    }
  ],
  "options": {
    "debug": true
  }
}
