### send with start and end
POST http://{{host}}/streams
Content-Type: application/json

{
  "sql": "CREATE STREAM triggerStream() WITH (TYPE=\"mqtt\",FORMAT=\"json\",DATASOURCE=\"trigger\",SHARED=\"true\");"
}

### send with start and end
PUT http://{{host}}/tables/nanoTable
Content-Type: application/json

{
  "sql": "CREATE TABLE nanoTable() WITH (TYPE=\"nano\",FORMAT=\"canmsg\",SCHEMAID=\"scene\/dbc\",KIND=\"lookup\",CONF_KEY=\"lookup\");"
}

### Get all
POST http://{{host}}/rules
Content-Type: application/json

{
  "id": "ruleFetch",
  "name": "测试所有数据",
  "sql": "SELECT * FROM triggerStream INNER JOIN nanoTable ON nanoTable.start = ts1 AND nanoTable.`end` = ts2",
  "actions": [
    {
      "mqtt": {
        "server": "tcp://syno.home:1883",
        "topic": "result/lookup",
        "sendSingle": true
      }
    }
  ]
}

### Send multiple batch data
#{"ts1":10000, "ts2": 20000}
