### 实时流
PUT http://{{host}}/streams/spiStream
Content-Type: application/json

{
  "sql": "CREATE STREAM spiStream() WITH (TYPE=\"mqtt\",FORMAT=\"spi\",DATASOURCE=\"canudp\",SCHEMAID=\"dbc\/geely\/geely.json\", SHARED=\"true\");"
}

### 实时采集
POST http://{{host}}/rules
Content-Type: application/json

{
  "id": "ruleAll",
  "name": "实时采集",
  "sql": "SELECT * FROM spiStream",
  "actions": [
    {
      "mqtt": {
        "server": "tcp://syno.home:1883",
        "topic": "result/all",
        "sendSingle": true
      }
    }
  ]
}

###
GET http://{{host}}/rules/ruleAll/status

#{
#  "status": "running",
#  "lastStartTimestamp": "1720670185585",
#  "lastStopTimestamp": "0",
#  "nextStopTimestamp": "0",
#  "source_spiStream_0_records_in_total": 6,
#  "source_spiStream_0_records_out_total": 6,
#  "source_spiStream_0_messages_processed_total": 6,
#  "source_spiStream_0_process_latency_us": 0,
#  "source_spiStream_0_buffer_length": 0,
#  "source_spiStream_0_last_invocation": "2024-07-11T12:02:04.236103",
#  "source_spiStream_0_exceptions_total": 1,
#  "source_spiStream_0_last_exception": "The connection to mqtt broker is lost due to EOF",
#  "source_spiStream_0_last_exception_time": "2024-07-11T12:00:54.586445",
#  "op_spiStream_2_decoder_0_records_in_total": 6,
#  "op_spiStream_2_decoder_0_records_out_total": 6,
#  "op_spiStream_2_decoder_0_messages_processed_total": 6,
#  "op_spiStream_2_decoder_0_process_latency_us": 3157660,
#  "op_spiStream_2_decoder_0_buffer_length": 0,
#  "op_spiStream_2_decoder_0_last_invocation": "2024-07-11T12:02:04.236103",
#  "op_spiStream_2_decoder_0_exceptions_total": 0,
#  "op_spiStream_2_decoder_0_last_exception": "",
#  "op_spiStream_2_decoder_0_last_exception_time": 0,
#  "op_3_project_0_records_in_total": 6,
#  "op_3_project_0_records_out_total": 6,
#  "op_3_project_0_messages_processed_total": 6,
#  "op_3_project_0_process_latency_us": 0,
#  "op_3_project_0_buffer_length": 0,
#  "op_3_project_0_last_invocation": "2024-07-11T12:02:07.394289",
#  "op_3_project_0_exceptions_total": 0,
#  "op_3_project_0_last_exception": "",
#  "op_3_project_0_last_exception_time": 0,
#  "op_mqtt_0_0_transform_0_records_in_total": 6,
#  "op_mqtt_0_0_transform_0_records_out_total": 6,
#  "op_mqtt_0_0_transform_0_messages_processed_total": 6,
#  "op_mqtt_0_0_transform_0_process_latency_us": 0,
#  "op_mqtt_0_0_transform_0_buffer_length": 0,
#  "op_mqtt_0_0_transform_0_last_invocation": "2024-07-11T12:02:07.394289",
#  "op_mqtt_0_0_transform_0_exceptions_total": 0,
#  "op_mqtt_0_0_transform_0_last_exception": "",
#  "op_mqtt_0_0_transform_0_last_exception_time": 0,
#  "op_mqtt_0_1_encode_0_records_in_total": 6,
#  "op_mqtt_0_1_encode_0_records_out_total": 6,
#  "op_mqtt_0_1_encode_0_messages_processed_total": 6,
#  "op_mqtt_0_1_encode_0_process_latency_us": 0,
#  "op_mqtt_0_1_encode_0_buffer_length": 0,
#  "op_mqtt_0_1_encode_0_last_invocation": "2024-07-11T12:02:07.394289",
#  "op_mqtt_0_1_encode_0_exceptions_total": 0,
#  "op_mqtt_0_1_encode_0_last_exception": "",
#  "op_mqtt_0_1_encode_0_last_exception_time": 0,
#  "sink_mqtt_0_0_records_in_total": 7,
#  "sink_mqtt_0_0_records_out_total": 5,
#  "sink_mqtt_0_0_messages_processed_total": 7,
#  "sink_mqtt_0_0_process_latency_us": 0,
#  "sink_mqtt_0_0_buffer_length": 0,
#  "sink_mqtt_0_0_last_invocation": "2024-07-11T12:02:07.394289",
#  "sink_mqtt_0_0_exceptions_total": 2,
#  "sink_mqtt_0_0_last_exception": "mqtt client is not connected",
#  "sink_mqtt_0_0_last_exception_time": "2024-07-11T12:00:54.588073"
#}

### 1s降采样流
POST http://{{host}}/streams
Content-Type: application/json

{
  "sql": "CREATE STREAM spiOneSec() WITH (TYPE=\"mqtt\",FORMAT=\"spi\",DATASOURCE=\"canudp\",SCHEMAID=\"dbc\/geely\/geely.json\", SHARED=\"true\", CONF_KEY=\"spi_1sec\");"
}

### ### 测试规则 1s 实时采集
POST http://{{host}}/rules
Content-Type: application/json

{
  "id": "ruleAll2",
  "name": "1s实时采集",
  "sql": "SELECT * FROM spiOneSec",
  "actions": [
    {
      "mqtt": {
        "server": "tcp://syno.home:1883",
        "topic": "result/all",
        "sendSingle": true
      }
    }
  ]
}

### 10s 周期性采集
POST http://{{host}}/rules
Content-Type: application/json

{
  "id": "rule10second",
  "name": "10s周期采集",
  "sql": "SELECT window_start() as startTime, rule_id() as identifier, \"1.0.0\" as signals_version, collect(*) as results FROM canmsgBatchStream GROUP BY TumblingWindow(ss, 10)",
  "actions": [
    {
      "mqtt": {
        "server": "tcp://127.0.0.1:1883",
        "topic": "result/c10",
        "sendSingle": true
      }
    }
  ]
}

### 10s 周期性采集并压缩
POST http://{{host}}/rules
Content-Type: application/json

{
  "id": "rule10secondCompress",
  "name": "10s周期采集并压缩",
  "sql": "SELECT window_start() as startTime, rule_id() as identifier, \"1.0.0\" as signals_version, collect(*) as results FROM canmsgBatchStream GROUP BY TumblingWindow(ss, 10)",
  "actions": [
    {
      "mqtt": {
        "server": "tcp://127.0.0.1:1883",
        "topic": "result/c10",
        "compression": "zstd",
        "sendSingle": true
      }
    }
  ]
}

### 10s 文件采集
PUT http://{{host}}/rules/rule10secondCSV
Content-Type: application/json

{
  "id": "rule10secondCSV",
  "name": "10s周期文件",
  "sql": "SELECT * FROM spiOneSec",
  "actions": [
    {
      "file": {
        "path": "data/mock.csv",
        "format": "delimited",
        "fileType": "csv",
        "hasHeader": true,
        "sendSingle": true,
        "rollingCount": 10,
        "rollingNamePattern": "suffix",
        "rollingHook":        "nano",
        "sendError": false,
        "rollingHookProps": {
          "server": "tcp://syno.home:1883",
          "topic": "result/filetran",
          "delete": 10
        }
      }
    }
  ]
}

### 场景一周期采集 10s 文件采集
POST http://{{host}}/rules
Content-Type: application/json

{
  "id": "rule10secondCSV_ZSTD",
  "name": "10s周期文件压缩",
  "sql": "SELECT * FROM canmsgBatchStream",
  "actions": [
    {
      "file": {
        "path": "data/mock.zstd",
        "format": "delimited",
        "fileType": "csv",
        "hasHeader": true,
        "sendSingle": true,
        "rollingCount": 10,
        "compression": "zstd",
        "rollingNamePattern": "suffix"
      }
    }
  ]
}

### 场景二 历史采集  30min 50信号

### 场景三 事件采集
PUT http://{{host}}/rules/ruleTriggerSample
Content-Type: application/json

{
  "id": "ruleTriggerSample",
  "name": "事件采集例子",
  "sql": "SELECT `PrivateInfoCAN.0x380.AcoustModSts`, `PrivateInfoCAN.0x380.AcoustModSts_UB`,`PrivateInfoCAN.0x380.AudioMuteSts` FROM spiStream GROUP BY TumblingWindow(ss, 30)",
  "actions": [
    {
      "mqtt": {
        "server": "tcp://syno.home:1883",
        "topic": "result/trigger",
        "format": "delimited",
        "hasHeader": true,
        "sendSingle": false
      }
    }
  ],
  "options": {
    "sendError": false
  }
}

###util
PUT http://{{host}}/rules/rulePick
Content-Type: application/json

{
  "id": "rulePickTest",
  "name": "事件采集例子",
  "sql": "SELECT `PropulsionCAN.0x178.HvSysLimnIndcn`, ts FROM spiStream GROUP BY SlidingWindow(ss, 1) OVER (WHEN ts - last_hit_time() > 2000)",
  "actions": [
    {
      "mqtt": {
        "server": "tcp://syno.home:1883",
        "topic": "result/pick",
        "format": "json",
        "sendSingle": false
      }
    }
  ],
  "options": {
    "sendError": false,
    "bufferLength": 100
  }
}

### rule pick 1
POST http://{{host}}/rules
Content-Type: application/json

{
  "id": "rulePickTest",
  "name": "事件采集例子",
  "sql": "SELECT `PropulsionCAN.0x331.HvBattCooltT`,`ZCU_CANFD2.0x491.BattIRaw`,`ZCU_CANFD1.0x180.BrkPedlPsdBrkPedlPsd`,`PropulsionCAN.0x315.HvBattTAvg`,`PropulsionCAN.0x315.HvBattTMax`,`PropulsionCAN.0x145.CellUMinId`,`ConnectivityCANFD.0x3C8.VehSpdAvgIndcdVehSpdIndcd`,`PropulsionCAN.0x145.CellUMaxId`,`PropulsionCAN.0x145.CellUMin`,`PropulsionCAN.0x142.HvBattCellUInfoU4`,`PropulsionCAN.0x315.HvBattTMin`,`ZCU_CANFD2.0x138.BattURaw`,`PropulsionCAN.0x178.HvSysLimnIndcn`,`PropulsionCAN.0x142.HvBattLimnIndcn`,`PropulsionCAN.0x116.AccrPedlPsdAccrPedlPsd`,`PropulsionCAN.0x145.CellUMax`,`PropulsionCAN.0x142.HvBattCellUInfoU3` FROM spiStream GROUP BY SlidingWindow(ss, 1) OVER (WHEN `PropulsionCAN.0x142.HvBattLimnIndcn` = 1 AND lag(`PropulsionCAN.0x142.HvBattLimnIndcn`) != 1)",
  "actions": [
    {
      "mqtt": {
        "server": "tcp://syno.home:1883",
        "topic": "result/pick",
        "format": "json",
        "sendSingle": false
      }
    }
  ],
  "options": {
    "sendError": false,
    "bufferLength": 100
  }
}

###util
POST http://{{host}}/rules
Content-Type: application/json

{
  "id": "rulePickAll",
  "name": "事件采集例子",
  "sql": "SELECT `PropulsionCAN.0x178.HvSysLimnIndcn` FROM spiStream",
  "actions": [
    {
      "mqtt": {
        "server": "tcp://syno.home:1883",
        "topic": "result/pickall",
        "format": "json",
        "sendSingle": true
      }
    }
  ],
  "options": {
    "sendError": false,
    "bufferLength": 100
  }
}

###
GET http://{{host}}/rules/rule10second/status