name: Run fvt tests

concurrency:
  group: fvt-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - "*"
    branches:
      - master
  pull_request:
    paths-ignore:
      - "docs/**"
      - "usage/**"
  release:
    types:
      - published

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  fvt_tests:
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      emqx:
        image: emqx/emqx:4.3.10
        ports:
          - 1883:1883
          - 18083:18083
    env:
      JMETER_VERSION: 5.4.3
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.24'
      - name: set git token
        run: git config --global url."https://${{ secrets.CI_GIT_TOKEN }}:x-oauth-basic@github.com/emqx".insteadOf "https://github.com/emqx"
      - uses: actions/checkout@v4
      - name: build kuiper
        run: |
          sudo apt-get update
          make build_fvt
          echo "KUIPER_LOG_PATH=_build/kuiper-$(git describe --tags --always)-$(uname -s | tr "[A-Z]" "[a-z]")-amd64/log" >> $GITHUB_ENV
      - name: run kuiper
        run: |
          bash ./test/setup_env.sh
      - name: run gee integration tests
        run: |
          go test ./test/fvt/...
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: '8' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Cache jmeter
        id: cache-jmeter
        uses: actions/cache@v4
        with:
          path: apache-jmeter.tgz
          key: apache-jmeter-${{ env.JMETER_VERSION }}
      - name: Download jmeter
        if: steps.cache-jmeter.outputs.cache-hit != 'true'
        timeout-minutes: 10
        env:
          JMETER_VERSION: ${{ env.JMETER_VERSION }}
        run: |
          wget --no-check-certificate --no-verbose -O apache-jmeter.tgz https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz
      - name: Install jmeter
        timeout-minutes: 10
        env:
          JMETER_VERSION: ${{ env.JMETER_VERSION }}
        run: |
          tar -xvf apache-jmeter.tgz -C /tmp
          echo "jmeter.save.saveservice.output_format=xml" >> /tmp/apache-jmeter-$JMETER_VERSION/user.properties
          echo "jmeter.save.saveservice.response_data.on_error=true" >> /tmp/apache-jmeter-$JMETER_VERSION/user.properties
          wget -O /tmp/apache-jmeter-$JMETER_VERSION/lib/ext/mqtt-xmeter-1.13-jar-with-dependencies.jar https://github.com/emqx/mqtt-jmeter/raw/master/Download/v1.13.0/mqtt-xmeter-1.13-jar-with-dependencies.jar
          ln -s /tmp/apache-jmeter-$JMETER_VERSION /opt/jmeter
      - name: run fvt tests
        timeout-minutes: 5
        run: bash ./test/run_jmeter.sh with_edgex=true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: kuiper_logs_with_edgex
          path: ${{ env.KUIPER_LOG_PATH }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jmeter_logs_with_edgex
          path: ./jmeter_logs
      - name: check logs
        run: |
          sudo apt-get update && sudo apt-get install -y libxml2-utils
          cd jmeter_logs
          for file in `ls *.jtl`
          do
            if [ ! -z "$(cat $file| grep '<failure>' | awk -F '>' '{print $2}' | awk -F '<' '{print $1}' | grep true)" ] ||
              [ "$(xmllint --format --xpath '/testResults/sample/@rc' $file | sed -r 's/ /\n/g;' | sort -u | grep -E 'rc=\"[45][0-9][0-9]\"|rc=\"\"')" != "" ]; then
                echo -e "---------------------------------------------\n"
                echo "FVT tests error for $file"
                exit 1
            fi
          done