name: Run fvt tests

concurrency:
  group: fvt-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - "*"
    branches:
      - master
  pull_request:
    paths-ignore:
      - "docs/**"
      - "usage/**"
  release:
    types:
      - published

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  fvt_tests:
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      emqx:
        image: emqx/emqx:4.3.10
        ports:
          - 1883:1883
          - 18083:18083
    env:
      JMETER_VERSION: 5.4.3
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.25.4'
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ vars.AUTH_APP_ID }}
          private-key: ${{ secrets.AUTH_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            lfek
            ekuiper_can
            can
            sdv-tools
            arxml-converter
            idl-parser

      - name: Configure Go environment
        run: |
          git config --global url."https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/".insteadOf "https://github.com/"
          go env -w GOPRIVATE=github.com/emqx/*

      - uses: actions/checkout@v4
      - name: run integration tests
        run: |
          go test -trimpath -race -tags "core compression ui prometheus sdv ex schema deadlock" ./test/fvt/...